### PR TITLE
[PR] Update `Flutter` Counter Example Docs 📝 

### LINKED ISSUE #5: Create Counter Example and Deploy to Mobile Device!
A counter is the "Hello World" of Apps. e.g: https://github.com/dwyl/phoenix-liveview-counter-tutorial
Our mission with this example/tutorial is to create the most basic possible counter in `Flutter` and get it running on a physical mobile device (e.g: one of the "Test" iPhones in the office)

# Todo

+ [x] Update this tutorial to be more beginner-friendly (e.g. add more context and step-by-step instructions)
+ [x] Run the counter on a **_real_ device** (not just the simulator) e.g. plug-in a Test iPhone (we have 2 of them in the office)
+ [x] Take photos/videos of the counter working on the **_real_ device** and upload them so that they can be included in the `README.md`
+ [x] Setup CI/CD (run the tests) on **GitHub Actions**: https://github.com/dwyl/flutter-counter-example/issues/6

Remember the purpose of this example is to give people a beginner-friendly intro to `Flutter` so that they can _eventually_ contribute to our **`App`**. So removing all barriers is _essential_! 🙏

### LINKED ISSUE #6: Chore: Run Tests on `GitHub`  Actions
# Story

As an engineer building a `Flutter` App, 🧑‍💻 
I want to run tests whenever new code is committed ⬆️ 
So that I know everything is working as expected. ✅ 

# Todo

+ [ ] Figure out how to run the test for this basic counter on **`GitHub` Actions**. 🔍 

> **Note**: the https://github.com/dwyl/flutter-todo-list-tutorial/pull/28 already has CI/CD running via: [`.github/workflows/ci.yml`](https://github.com/dwyl/flutter-todo-list-tutorial/blob/master/.github/workflows/ci.yml)  👀 
this will be a good starting point for your quest. 🚀 
The versions of `Java` and `Flutter` will need to be updated but the rest should be useful. 🤞 

Please leave as many comments as you can on this issue in your quest to get the tests running on **`GitHub` Actions**. 💬 
This is a bit of an "unknown" for us because we have limited `Flutter` experience so this needs to be very well documented. 🙏

### PR DESCRIPTION
**Pull request by LuchoTurtle**
fixes #5
fixes #6 

This PR is kind of an overhaul to the project, using up-to-date packages and the newest Dart and Flutter version. The README is revamped and should be more explicit and show code coverage as well.

I'm still busy rewriting the README, so it's still in progress.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
I've added a `ci.yml` file for the Github Action pipeline with Codecov. However, I don't know how to test this without having to merge to the `main` branch :/

**Comment by nelsonic** [comment]
@LuchoTurtle see: https://github.com/dwyl/flutter-counter-example/issues/6#issuecomment-1316622078 👀 
Create a _separate_ PR to add GitHub CI and @dependabot to the repo. We'll merge it _fast_ and then you can continue with your day. 👌

**Comment by LuchoTurtle** [comment]
There is a section that explains how to add CI. Since, in this project, CI is dependant on this PR, we should get it merged and if it doesn't work, I can create a micro-PR to fix anything that is wrong, both on the `yml` file and the README.

**Comment by LuchoTurtle** [comment]
Fixed the CI. It's not running correctly because it seems to be "confusing" with files that aren't on `main` but are present on this PR. 
After merging it should work. If it doesn't, I can fix it.

**Review by nelsonic — APPROVED** [review]
Looks good. 👌 
We could tidy the `README.md` a bit, but not urgent. 💭 
:shipit:

**Pull request merged**
